apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: "{{app_name}}"
    commit_sha: "{{commit_sha}}"
  name: "{{app_name}}"
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "{{app_name}}"
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: "{{app_name}}"
        commit_sha: "{{commit_sha}}"
        # redeploy: "$(date +%s)"
    spec:
      imagePullSecrets:
        - name: docker-terabits
      containers:
        - image: "{{docker_fdqn}}/home/{{app_name}}:{{img_tag}}"
          imagePullPolicy: Always
          name: "{{app_name}}"
          env:
            - name: SECRET_KEY
              value: "{{secret_key}}"
            - name: MONGO_URI
              value: "{{mongo_uri}}"
            - name: SANSCRIPT_UTILS_URL
              value: "{{sanscript_utils_url}}"
            - name: DIRECTUS_API_URL
              value: "{{directus_api_url}}"
            - name: DIRECTUS_USER_AUTH_TOKEN
              value: "{{directus_user_auth_token}}"
          ports:
            - containerPort: {{app_port | int}}
              protocol: TCP
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: "{{app_name}}"
  namespace: default
spec:
  selector:
    app: "{{app_name}}" # pod label
  ports:
    - protocol: TCP
      port: 80 # port to be exposed on service
      targetPort: {{app_port | int}} # port on the pod
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: "{{app_name}}"
  namespace: default
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{app_fqdn}}`)
      kind: Rule
      services:
        - name: "{{app_name}}"
          port: 80        
  tls:
    secretName: cert-terabits-io-tls
