ssh_user: "{{ vault_ssh_user }}"

server_domain: "local.{{vault_server_domain}}"
docker_fdqn: "docker.local.{{vault_server_domain}}"

git_tag: "latest"

secret_key: "{{vault_secret_key}}"

mongodb_host: "docker-ct.local.io"
mongodb_port: "{{vault_mongodb_port}}"
mongodb_db: "{{vault_mongodb_db}}"
mongodb_user: "{{vault_mongodb_user}}"
mongodb_pwd: "{{vault_mongodb_pwd}}"

mongo_db_name: "{{vault_mongodb_db}}"

mongo_uri: "mongodb://{{mongodb_user}}:{{mongodb_pwd}}@{{mongodb_host}}:{{mongodb_port}}/?authMechanism=DEFAULT&authSource={{mongodb_db}}"
database_url: "mongodb://{{mongodb_user}}:{{mongodb_pwd}}@{{mongodb_host}}:{{mongodb_port}}/{{mongodb_db}}?authSource={{mongodb_db}}"
push_msg_vapid_public_key: "{{vault_push_msg_vapid_public_key}}"
push_msg_vapid_private_key: "{{vault_push_msg_vapid_private_key}}"